### ISSUE TITLE
Unable to calculate FID

### ISSUE THREAD

**Issue by xbyym** [LTH14/mar#41]
Thank you for your great work！ 
I encountered an issue while calculating FID: I used custom parameters: num_images: 64, num_iter: 64, eval_bsz: 2; however, it resulted in an error indicating that the input2 parameter is required. Could you please tell me where the problem might be?"
![QQ_1726285703044](https://github.com/user-attachments/assets/3210ad3a-f0ab-4842-85b1-3343ec535620)

Traceback (most recent call last):
  File "/root/mar/main_mar.py", line 313, in <module>
    main(args)
  File "/root/mar/main_mar.py", line 264, in main
    evaluate(model_without_ddp, vae, ema_params, args, 0, batch_size=args.eval_bsz, log_writer=log_writer,
  File "/root/mar/engine_mar.py", line 199, in evaluate
    metrics_dict = torch_fidelity.calculate_metrics(
  File "/root/miniconda3/envs/mar/lib/python3.8/site-packages/torch_fidelity/metrics.py", line 209, in calculate_metrics
    vassert(input2 is not None or not need_input2, 'Second input is required for "fid" and "kid" metrics')
  File "/root/miniconda3/envs/mar/lib/python3.8/site-packages/torch_fidelity/helpers.py", line 9, in vassert
    raise ValueError(message)
ValueError: Second input is required for "fid" and "kid" metrics

**Comment by LTH14** [comment]
Can you check whether your torch_fidelity version is correct? We use a customized torch-fidelty to support pre-computed imagenet statistics ```pip install -e git+https://github.com/LTH14/torch-fidelity.git@master#egg=torch-fidelity```

**Comment by xbyym** [comment]
Thank you very much, I have resolved my issue.
